### PR TITLE
fix: update for nuxt RC.9

### PR DESCRIPTION
**Pull request by gravitano**
Update for [nuxt RC.9](https://github.com/nuxt/framework/discussions/7186)

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

- Update nuxt version constraint
- Migrate auto-imports hook

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by Intevel** [comment]
@gravitano You can close this PR, it was done with https://github.com/nuxt-modules/strapi/commit/6767cf016d83dbb1b085532a683959ed85df4f1f

**Comment by gravitano** [comment]
Thank you @Intevel

**Comment by benjamincanac** [comment]
@gravitano Sorry, I did the changes before seing your pull request! 🙏

**Comment by gravitano** [comment]
That’s OK 👌

**Pull request closed without merging**
