### PR TITLE
Eliminate Deprecated DNS Module Import

### PR DESCRIPTION
**Pull request by ram-you**
This PR addresses a deprecated DNS module import, following Vite's documentation guidance. Vite discourages the use of Node.js modules in the browser due to potential bundle size increase. The import block has been removed, aligning the codebase with recommended practices for more efficient and browser-compatible builds. The adjustment reflects Vite's emphasis on minimizing the inclusion of Node.js-specific modules in client-side code. 

I would like to extend my sincere apologies for any inconvenience caused by the recent pull request [https://github.com/nuxt-modules/strapi/pull/370](url).
After careful reconsideration, I've recognized an error in my assessment, and the changes made in the previous pull request were not aligned with the best interests of the project. This new pull request aims to definitely remove the DNS module import, ensuring that the application's functionality is maintained as intended. I appreciate your understanding, and I apologize for any confusion caused.

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Vite recommend avoiding Node.js modules for browser code to reduce the bundle size

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by benjamincanac** [comment]
Why would you remove this? I've just added this to fix the cookie being removed on localhost with Node 18 as you can read in the comment above this code.

**Comment by ram-you** [comment]
> Why would you remove this? I've just added this to fix the cookie being removed on localhost with Node 18 as you can read in the comment above this code.


Hi @benjamincanac, thank you for your comment. I removed the code because Vite was still generating a warning despite the fix. The warning message indicates that the "dns" module has been externalized for browser compatibility. You can find more details about this warning [here](http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility). 
I'll explore alternative solutions to resolve the cookie issue. 
I appreciate your understanding.

**Comment by ram-you** [comment]
Hi @benjamincanac 
To address the Vite "Warning" issue while retaining your solution for "the cookie being removed on localhost with Node 18", I have created a Nuxt Server Plugin in my project named "/plugins/dns_ipv4first.server.ts" with the following code:
```js
export default defineNuxtPlugin({
  name: 'dns_ipv4first',
  parallel: true,
  async setup (nuxtApp) {
    // Fixes `ECONNREFUSED` on Node 18: https://github.com/node-fetch/node-fetch/issues/1624#issuecomment-1407717012
    // Import dns only if running in a server environment during development
    if (import.meta.env.DEV) {
      try {
        const dns = await import("dns");
        await dns.setDefaultResultOrder("ipv4first");
      } catch (error) {
        console.error("Error importing dns module:", error);
      }
    }
  }
});

```

And the issue is resolved. What do you think of my approach?

**Comment by benjamincanac** [comment]
It works for me! Do you feel like updating your PR with this? 😊 

Why `import.meta.env.DEV` instead of `process.dev`?

If you make this change I would create a plugins dir inside `runtime` and rename `strapi.plugin` -> `strapi`. You could now add this `dns.server.ts` inside this `plugins` dir.

**Comment by benjamincanac** [comment]
I can push directly if you prefer, just let me know!

**Comment by ram-you** [comment]
> I can push directly if you prefer, just let me know!

Yes please

**Comment by benjamincanac** [comment]
Closing in favor of https://github.com/nuxt-modules/strapi/commit/13aa06317e215f5e0b170871631b290d711c0f80

**Comment by benjamincanac** [comment]
Thanks @ram-you!

**Pull request closed without merging**
