### PR TITLE
fix nuxt cookies check condition and set cookie value

### PR DESCRIPTION
**Pull request by ozireh**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

- Add of a check for the value key in the first condition 
- Change the cookie setter method

As we return a RefImpl Object, the check for the value key was missing on the first condition I guess. For the second change, the value setter was not properly updating the cookie.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by benjamincanac** [comment]
Hello @ozireh,

Would you be able to explain what you're trying to solve here? I've been using the strapi module for a while now and didn't have any issue with cookies.

**Comment by ozireh** [comment]
> Hello @ozireh,
> 
> Would you be able to explain what you're trying to solve here? I've been using the strapi module for a while now and didn't have any issue with cookies.

Hey @benjamincanac,

Apologies for the delayed response. I took the time to reproduce the issue and gather more precise details.

### Purpose:
I'm attempting to make protected requests using the useStrapiClient composable with an API Token Authorization from Strapi. I noticed that the token can be set as a cookie in the nuxt.config.js file using the cookie option.

### Problem:
The API Token is not present in the request.

### Process:
To investigate it, I created an empty Nuxt project with the following package.json configuration:

```javascript
"devDependencies": {
    "@nuxtjs/strapi": "^1.9.1",
    "@types/node": "^18",
    "nuxt": "^3.5.1"
}
```

The project runs on Node v18.14.1.
It's possible that there might be a misunderstanding on my part regarding the usage. Here is my process:

In my nuxt.config.ts file, I have the following configuration:

```javascript
export default defineNuxtConfig({
  modules: [
    '@nuxtjs/strapi'
  ],
  strapi: {
    url: process.env.STRAPI_URL || 'http://localhost:1337',
    prefix: '/api',
    version: 'v4',
    cookie: {
      default: () => "STRAPI_API_TOKEN",
      watch: false
    },
    cookieName: 'strapi_jwt'
  }
})
```

_Note: although the cookie option should be an object, I have also tried passing just a string, but without success:_

```javascript
cookie: <any> "STRAPI_API_TOKEN"
```

Upon further investigation of the code, I noticed that useStrapiClient utilizes the useStrapiToken composable, which, in my case, doesn't properly return the cookie.

### My proposed changes

**In the file src/runtime/composables/useStrapiToken.ts on line 8**
I added ?.value because nuxt._cookies.[config.strapi.cookieName] will never be null (as we're accessing a ref object), but nuxt._cookies.[config.strapi.cookieName].value potentially can be.

**In the file src/runtime/composables/useStrapiToken.ts on lines 12 and 13**
Even if config.strapi.cookie isn't null, the cookie value is always null:

```javascript
const cookie = useCookie<string | null>(config.strapi.cookieName, config.strapi.cookie)
console.log(cookie.value); // output: null
```

To address this, I split the process of setting the new cookie value into two steps:

First, I retrieve the cookie value by passing only the cookieName:

```javascript
const cookie = useCookie<string | null>(config.strapi.cookieName)
```

Then, I set the value with this line:

```javascript
cookie.value = config.strapi.cookie
```

Hope this clarifies the issue my proposed changes. Once again, sorry if I misunderstood something about the usage of this cookie option. Let me know if you have any further questions or need more information.

**Comment by benjamincanac** [comment]
Why would you want to set your api token in cookie instead of passing it as header manually?

```ts
const client = useStrapiClient()

await client('/restaurants', {
  headers: {
    Authorization: process.env.STRAPI_API_TOKEN
  }
})
```

**Comment by ozireh** [comment]
> ```ts
> useStrapiClient()
> ```

Yes, that's what I finally did, more or less. Since I had multiple requests, I wrapped them into a custom composable to avoid repetitions. The main purpose of this pull request was to fix the useStrapiToken composable, which is still not functioning correctly.

My initial instinct was to use the tools provided by the module. According to the documentation [(https://strapi.nuxtjs.org/setup),](https://strapi.nuxtjs.org/setup), there is a configurable cookie parameter in the config that should be used in the useStrapiToken composable, and subsequently, in the useStrapiClient if we look the code.

**Comment by benjamincanac** [comment]
I still don't see why you would want to store a private API token into each client cookies.

**Comment by benjamincanac** [comment]
Which feature do you mean? Cookies?

**Comment by ozireh** [comment]
Ok, my bad! useStrapiToken is related to authentication. Sorry for the misunderstanding.

**Pull request closed without merging**
